backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "struktur_organisasi"
    label: "Struktur Organisasi"
    files:
      - label: "Struktur Organisasi Data"
        name: "struktur_organisasi"
        file: "assets/data/struktur-organisasi.json"
        fields:
          - label: "Members"
            name: "members"
            widget: "list"
            fields:
              - { label: "Nama", name: "nama", widget: "string" }
              - { label: "Gambar", name: "gambar", widget: "image" }
              - { label: "Jabatan", name: "jabatan", widget: "string" }